In [2]:
from sklearn import linear_model
import pandas as pd

In [9]:
# read excel to build a dataframe
df = pd.read_excel("~/Documents/zf/SIT/BIA686/CASE4/ForAnalysis.xlsx")
df.head()

   Amount_of_credits  Value_of_savings  prev_credits
0               2145                 0           2.5
1              12204              1000           1.0
2              10974                 0           2.5
3               6419                 0           2.5
4               1258                 0           1.0

In [13]:
# define x, y as independent and dependent variables
X = df[["Value_of_savings", "prev_credits"]]
Y = df["Amount_of_credits"]

In [15]:
# initalize the linear model and fit it into X and Y
lm = linear_model.LinearRegression()
model = lm.fit(X,Y)

In [24]:
# predict the Y based on the generated model
predictions = lm.predict(X)
df_res = pd.DataFrame(predictions, columns = ["predict_credits"])

In [28]:
# sort predict_credicts for first 50 customers in descending order
df_res.sort_values(by = "predict_credits", ascending = False)[0:49]

     predict_credits
791      3928.467924
519      3928.467924
65       3835.070841
168      3835.070841
66       3710.541396
78       3710.541396
646      3710.541396
913      3710.541396
821      3710.541396
921      3710.541396
818      3710.541396
923      3710.541396
740      3710.541396
417      3710.541396
169      3710.541396
665      3710.541396
399      3710.541396
560      3710.541396
558      3710.541396
932      3710.541396
50       3710.541396
903      3710.541396
305      3710.541396
643      3710.541396
104      3710.541396
866      3710.541396
349      3710.541396
341      3710.541396
617      3710.541396
619      3710.541396
603      3710.541396
622      3710.541396
105      3710.541396
880      3710.541396
84       3710.541396
884      3710.541396
98       3710.541396
328      3710.541396
846      3710.541396
317      3710.541396
840      3710.541396
308      3710.541396
86       3710.541396
675      3710.541396
290      3710.541396
345      3710.541396
7        3710.541396
697      3710.541396
437      3710.541396